#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

wall="/usr/share/wallpapers/frikios/Stormtrooper.png"
riverctl keyboard-layout  -variant altgr-intl us

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of alacritty
riverctl map normal Super Return spawn alacritty

# run rofi
riverctl map normal Super+Shift m spawn  "~/.config/rofi/launchers/type-2/launcher.sh"

# run powermenu
riverctl map normal Super+Shift p spawn "~/.config/rofi/powermenu/type-2/powermenu.sh"

# lock screen 
riverctl map normal Super+Shift b spawn "swaylock -e -f -i ${wall}"

# run applications
riverctl map normal Super+Shift y spawn "MOZ_ENABLE_WAYLAND=1 firefox"
riverctl map normal Super+Shift t spawn "MOZ_ENABLE_WAYLAND=1 thunderbird"
riverctl map normal Super+Shift f spawn "darktable"
riverctl map normal Super+Shift o spawn "libreoffice --writer"
riverctl map normal Super+Shift a spawn "kcalc"
riverctl map normal Super+Shift d spawn "dolphin"
riverctl map normal Super+Shift v spawn "pavucontrol"

# Super+n to close the focused view
riverctl map normal Super+Shift n close

# Super+Shift+E logout user
riverctl map normal Super+Shift e spawn "loginctl terminate-user ${USER}"

# Shutdown
riverctl map normal Super+Shift s spawn "loginctl poweroff"

# reboot
riverctl map normal Super+Shift r spawn "loginctl reboot"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 8)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x000000
riverctl border-color-focused 0x0d62ac
riverctl border-color-unfocused 0x111111
riverctl border-color-urgent 0xb63625
riverctl border-width 2

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl float-filter-add "float"
riverctl float-filter-add "popup"
riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl rule-add -app-id "firefox" ssd
riverctl rule-add -app-id "thunderbird-esr" ssd
riverctl rule-add -app-id "pavucontrol" ssd
riverctl rule-add -app-id "org.inkscape.Inkscape" ssd
riverctl rule-add -app-id "libreoffice-writer" ssd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-count 2  &

# autostart
riverctl spawn "wlr-randr --output HDMI-A-1 --mode 1920x1080@74.973000" 
riverctl spawn "dbus-update-activation-environment --all" 
riverctl spawn "/usr/lib/libexec/pipewire-launch.sh" 
riverctl spawn "/usr/lib/libexec/polkit-kde-authentication-agent-1" 
riverctl spawn "/usr/bin/dunst -config ~/.config/dunst/dunstrc" 
riverctl spawn "gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'" 
riverctl spawn "gsettings set org.gnome.desktop.interface icon-theme  'Papirus'" 
riverctl spawn "gsettings set org.gnome.desktop.interface cursor-theme 'Breeze_Snow'" 
riverctl spawn "gsettings set org.gnome.desktop.interface font-name 'Noto Sans 8'" 
riverctl spawn "waybar" 
# apply wallpaper
riverctl spawn "swaybg -m fill -i ${wall}"
