#!/bin/bash

volume_up() {
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
}
volume_down() {
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
}
volume_mute() {
	wpctl set-mute  @DEFAULT_SINK@ toggle
}
power_off() {
	systemctl poweroff
}
power_reboot() {
	systemctl reboot
}
pause_player() {
	playerctl play-pause
}
next_player() {
	playerctl next
}
previous_player() {
	playerctl previous
}
print_screenshot() {
	capture="$(xdg-user-dir PICTURES)/capturas/$(date +'%s_grim.png')"
	grim $capture
	notify-send -i /usr/share/icons/Papirus-Dark/32x32/status/messagebox_info.svg "Screenshot created!" "$capture"
}
runbmenu() {
	bemenu-run -i -l 16 \
	    --fb '#121212' \
	    --ff '#f7f2b8' \
	    --nb '#121212' \
	    --nf '#f7f2b8' \
	    --tb '#121212' \
	    --hb '#186873' \
	    --tf '#186873' \
	    --hf '#f7f2b8' \
	    --af '#f7f2b8' \
	    --sb '#186873' \
	    --sf '#f7f2b8' \
	    --fn 'Ubuntu bold 10' -H 20 -C -b  -p Apps
}
$1
