[colors.bright]
black = "0x000000"
blue = "0x2fa6c7"
cyan = "0x53998e"
green = "0x3db36e"
magenta = "0xd36a7d"
red = "0xe66456"
white = "0xffffff"
yellow = "0xf1b213"

[colors.normal]
black = "0x000000"
blue = "0x2fa6c7"
cyan = "0x53998e"
green = "0x3db36e"
magenta = "0xd36a7d"
red = "0xe66456"
white = "0xffffff"
yellow = "0xf1b213"

[colors.primary]
background = "0x121212"
foreground = "0xdfdfdf"
