# Forest Ivan Ruano Monjas

[colors.bright]
black   = "#191919"
red     = "#a46863"
green   = "#52c1ae"        # verde-azulado más vivo
yellow  = "#b6b476"
blue    = "#54a8bb"
magenta = "#9189aa"
cyan    = "#60d3c3"        # acento teal luminoso
white	= "#f7f2b8"
[colors.normal]
black   = "#191919"
red     = "#8a5a57"        # rojo corteza apagado
green   = "#3e9f91"        # verde-azulado oscuro (tono principal)
yellow  = "#9fa86d"        # amarillo musgo muy tenue
blue    = "#3e89a0"        # azul petróleo
magenta = "#7c7595"        # violeta gris frío
cyan    = "#44b4a8"        # teal brillante controlado
white	= "#f7f2b8"

[colors.primary]
background = "#121212"
foreground = "#f7f2b8"

[colors.cursor]
text = "#121212"
cursor = "#f7f2b8"

