# Glacier Ivan Ruano Monjas

[colors.bright]
black   = "#404a55"
red     = "#bd0f2f"
green   = "#49e998"
yellow  = "#fddf6e"
blue    = "#2a8bc1"
magenta = "#ea4727"
cyan    = "#a0b6d3"
white	= "#ffffff"

[colors.normal]
black   = "#2e343c"
red     = "#bd0f2f"
green   = "#35a770"
yellow  = "#fb9435"
blue    = "#1f5872"
magenta = "#bd2523"
cyan    = "#778397"
white	= "#ffffff"

[colors.primary]
background = "#0c1115"
foreground = "#ffffff"
