# Hacktober Ivan Ruano Monjas

[colors.bright]
black   = "#464444"
red     = "#b33323"
green   = "#42824a"
yellow  = "#c75a22"
blue    = "#5389c5"
magenta = "#e795a5"
cyan    = "#ebc587"
white	= "#ffffff"

[colors.normal]
black   = "#191918"
red     = "#b34538"
green   = "#587744"
yellow  = "#d08949"
blue    = "#206ec5"
magenta = "#864651"
cyan    = "#ac9166"
white	= "#f1eee7"

[colors.primary]
background = "#121212"
foreground = "#c9c9c9"
