# Moon Ivan Ruano Monjas

[colors.normal]
black   = "#191919"
red     = "#b24b30"
green   = "#28a0a2"
yellow  = "#d99800"
blue    = "#2882aa"
magenta = "#7b3d8a"
cyan    = "#0790a0"
white   = "#f7f2b8"

[colors.bright]
black   = "#2a2a2a"
red     = "#da5b40"
green   = "#30b0b2"
yellow  = "#e0b000"
blue    = "#3a9acc"
magenta = "#9050b0"
cyan    = "#33b0c0"
white   = "#fcf8d1"

[colors.primary]
background = "#121212"
foreground = "#f7f2b8"
