# Tokyo night Ivan Ruano Monjas

[colors.primary]
background = "#1a1b26"  # Azul oscuro profundo
foreground = "#c0caf5"  # Texto claro ligeramente azulado

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.selection]
text = "#1a1b26"
background = "#c0caf5"

[colors.normal]
black   = "#1a1b26"
red     = "#f7768e"  # Rojo rosado (Tokyo Night)
green   = "#9ece6a"  # Verde vibrante (Tokyo Night)
yellow  = "#e0af68"  # Amarillo cálido (Jellybeans touch)
blue    = "#7aa2f7"  # Azul brillante
magenta = "#bb9af7"  # Magenta suave
cyan    = "#7dcfff"  # Cian vivo
white   = "#a9b1d6"  # Gris claro

[colors.bright]
black   = "#414868"
red     = "#ff9e9e"
green   = "#b9f27c"
yellow  = "#ffda7b"
blue    = "#9ab8ff"
magenta = "#c7a5ff"
cyan    = "#89ddff"
white   = "#c0caf5"

[colors.hints]
start = { foreground = "#e0af68", background = "#1a1b26" }
end   = { foreground = "#1a1b26", background = "#e0af68" }

[colors.search]
matches = { foreground = "#1a1b26", background = "#e0af68" }
focused_match = { foreground = "#1a1b26", background = "#9ece6a" }

[colors.vi_mode_cursor]
text = "#1a1b26"
cursor = "#7aa2f7"

