# Tomorrow Ivan Ruano Monjas

[colors.primary]
background = "#121212"
foreground = "#eaeaea"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#eaeaea"

[colors.selection]
text = "#000000"
background = "#eaeaea"

[colors.normal]
black   = "#000000"
red     = "#d54e53"
green   = "#b9ca4a"
yellow  = "#e7c547"
blue    = "#7aa6da"
magenta = "#c397d8"
cyan    = "#70c0b1"
white   = "#eaeaea"

[colors.bright]
black   = "#666666"
red     = "#ff3334"
green   = "#9ec400"
yellow  = "#e7c547"
blue    = "#7aa6da"
magenta = "#b77ee0"
cyan    = "#54ced6"
white   = "#ffffff"
